import serviceImg from "../../assets/images/service.png";
export default {
    footList:[
        {name:"home",txt:"首页",icon:"&#xe605;",path:"/index/home"},
        {name:"find",txt:"爱聊",icon:"&#xe658;",path:"/index/find"},
        {name:"my",txt:"我的",icon:"&#xe603;",path:"/index/my"},
    ],
    hfoot:[
        {name:"fangyuan",txt:"房源",icon:"&#xe605;",path:"/hourse/fangyuan"},
        {name:"fujin",txt:"附近",icon:"&#xe655;",path:"/hourse/fujin"},
        {name:"map",txt:"地图",icon:"&#xe613;",path:"/hourse/map"},
        {name:"history",txt:"历史",icon:"&#xe604;",path:"/hourse/history"},
    ],
    homeico:[
        {name:"ershou",txt:"二手房",icon:"&#xe6fd;",path:"/hourse/ershou"},
        {name:"tenement",txt:"租房",icon:"&#xe65c;",path:"/hourse/tenement"},
        {name:"village",txt:"小区",icon:"&#xe626;",path:"/hourse/village"},
        {name:"store",txt:"门店",icon:"&#xe71b;",path:"/hourse/store"},
        {name:"agent",txt:"经纪人",icon:"&#xe63f;",path:"/hourse/agent"},
        {name:"mapsearch",txt:"地图找房",icon:"&#xe6bf;",path:"/hourse/mapsearch"},
        {name:"entrust",txt:"委托服务",icon:"&#xe659;",path:"/hourse/entrust"},
        {name:"contract",txt:"合同查询",icon:"&#xe627;",path:"/hourse/contract"},
    ],
    username:"",
    password:"",
    rpassword:"",
    json:"",
    show:true,
    banner:"",
    ershou:"",
    tenement:"",
    village:"",
    store:"",
    agent:"",
    operation:true,
    serviceimg:serviceImg,
    house:"",
}

